import {
  LucideBookOpenText,
  LucideCalendarDays,
  LucideCalculator,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleAlert,
  LucideCircleCheckBig,
  LucideCopy,
  LucideCreditCard,
  LucideDatabaseBackup,
  LucideDownload,
  LucideEgg,
  LucideEllipsisVertical,
  LucideHistory,
  LucideHouse,
  LucideList,
  LucideListTodo,
  LucideLogOut,
  LucideMapPin,
  LucideMessageCircle,
  LucidePencil,
  LucidePackage2,
  LucidePhone,
  LucidePiggyBank,
  LucidePlus,
  LucidePrinter,
  LucideReceipt,
  LucideReceiptText,
  LucideArchiveRestore,
  LucideSearch,
  LucideShare2,
  LucideUpload,
  LucideTrash2,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideTrophy,
  LucideUserRound,
  LucideUsers,
  LucideX,
  LucideBanknote,
  type LucideIconData,
} from '@lucide/angular';

export const UI_ICON_FALLBACK = LucideCircleAlert.icon;

export const UI_ICON_MAP: Record<string, LucideIconData> = {
  account_circle: LucideUserRound.icon,
  add: LucidePlus.icon,
  banknote: LucideBanknote.icon,
  calendar_month: LucideCalendarDays.icon,
  calculate: LucideCalculator.icon,
  chat: LucideMessageCircle.icon,
  check_circle: LucideCircleCheckBig.icon,
  chevron_left: LucideChevronLeft.icon,
  chevron_right: LucideChevronRight.icon,
  close: LucideX.icon,
  content_copy: LucideCopy.icon,
  database_backup: LucideDatabaseBackup.icon,
  download: LucideDownload.icon,
  egg: LucideEgg.icon,
  emoji_events: LucideTrophy.icon,
  edit: LucidePencil.icon,
  error: LucideCircleAlert.icon,
  history: LucideHistory.icon,
  home: LucideHouse.icon,
  inventory_2: LucidePackage2.icon,
  list: LucideList.icon,
  logout: LucideLogOut.icon,
  menu_book: LucideBookOpenText.icon,
  more_vert: LucideEllipsisVertical.icon,
  pending_actions: LucideListTodo.icon,
  people: LucideUsers.icon,
  phone: LucidePhone.icon,
  place: LucideMapPin.icon,
  point_of_sale: LucideCreditCard.icon,
  print: LucidePrinter.icon,
  receipt: LucideReceipt.icon,
  receipt_long: LucideReceiptText.icon,
  restore: LucideArchiveRestore.icon,
  savings: LucidePiggyBank.icon,
  search: LucideSearch.icon,
  share: LucideShare2.icon,
  trending_up: LucideTrendingUp.icon,
  upload: LucideUpload.icon,
  delete: LucideTrash2.icon,
  warning: LucideTriangleAlert.icon,
};
